name: petfriends-seo
on:
  push:
  pull_request:
  schedule:
    - cron: "*/60 * * * *"
jobs:
  fetch:
    name: check
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: 테스트 텔레그램
        run: |
          npm install
          npm run check
