name: youth-job-search
on:
  push:
  pull_request:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  fetch:
    name: check
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: 테스트 텔레그램
        run: |
          npm install
          curl --ciphers DEFAULT@SECLEVEL=1 "https://www.youthcenter.go.kr/board/boardList.do?bbsNo=3&pageUrl=board/board" > result
          npm run check-crawler
